version: '3'

services:
  web:
    build: .
    restart: always
    command: npm start
    volumes:
      - .:/usr/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
      - telegraf
#   deploy:
#     replicas: 5
#     restart_policy:
#       condition: on-failure
#     resources:
#       limits:
#         cpus: "0.1"
#         memory: 50M
#   network:
#     - webnet

  influxdb:
    image: influxdb:alpine
    restart: always
    command: "/usr/bin/influxd -config /etc/influxdb/influxdb.conf"
    volumes: 
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
    expose:
      - "8086"
    ports:
      - "8086:8086"
#   networks:
#     - webnet
  
  telegraf:
    image: telegraf:alpine
    restart: always
    command: "/usr/bin/telegraf -config /etc/telegraf/telegraf.conf"
    expose:
      - "8125/udp"
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
#   networks:
#     - webnet
      
#networks:
#  webnet:
